services:
  mongodb:
    image: mongo:7.0
    container_name: devsecops-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: devsecops-app
    ports:
      - "8085:8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/devsecops
    depends_on:
      - mongodb

volumes:
  mongodb_data:
