apiVersion: v1
kind: ConfigMap
metadata:
  name: devsecops-config
  namespace: devsecops
  labels:
    app: devsecops-app
data:
  SPRING_PROFILES_ACTIVE: "production"
  SERVER_PORT: "8080"
  MONGODB_DATABASE: "devsecops"
